package server

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/gorilla/mux"
	"github.com/maxiofs/maxiofs/internal/cluster"
	"github.com/maxiofs/maxiofs/internal/config"
	idpkg "github.com/maxiofs/maxiofs/internal/idp"
	"github.com/maxiofs/maxiofs/internal/replication"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// startAt builds a server on dir as a deployment that configures neither
// auth.jwt_secret nor auth.encryption_secret starts: with a JWT secret
// generated anew.
func startAt(t *testing.T, dir string) *Server {
	t.Helper()
	b := make([]byte, 16)
	_, err := rand.Read(b)
	require.NoError(t, err)
	srv, err := New(&config.Config{
		Listen: "127.0.0.1:0", ConsoleListen: "127.0.0.1:0", DataDir: dir, LogLevel: "error",
		PublicAPIURL: "http://localhost:8080", PublicConsoleURL: "http://localhost:8081",
		Storage: config.StorageConfig{Backend: "filesystem", Root: filepath.Join(dir, "storage")},
		Auth:    config.AuthConfig{EnableAuth: true, JWTSecret: hex.EncodeToString(b), JWTSecretAutoGenerated: true},
		Audit:   config.AuditConfig{RetentionDays: 7, DBPath: filepath.Join(dir, "audit.db")},
	})
	require.NoError(t, err)
	return srv
}

// storeCredentials stores, on s, one credential of each component that
// encrypts them, and returns the share's ID.
func storeCredentials(t *testing.T, s *Server) string {
	t.Helper()
	ctx := context.Background()
	now := time.Now().Unix()
	share, err := s.shareManager.CreateShare(ctx, "b", "k", "", "AKID", "share-secret-key", "u", nil)
	require.NoError(t, err)
	require.NoError(t, s.replicationManager.CreateRule(ctx, &replication.ReplicationRule{ID: "rule-1", TenantID: "t",
		SourceBucket: "b", DestinationEndpoint: "https://dest.example.com", DestinationBucket: "d",
		DestinationAccessKey: "AK", DestinationSecretKey: "rule-secret-key", Enabled: true,
		Mode: replication.ModeRealTime, ConflictResolution: replication.ConflictLWW}))
	require.NoError(t, s.idpManager.CreateProvider(ctx, &idpkg.IdentityProvider{ID: "idp-1", Name: "corp",
		Type: idpkg.TypeLDAP, Status: idpkg.StatusActive, CreatedBy: "admin", CreatedAt: now, UpdatedAt: now,
		Config: idpkg.ProviderConfig{LDAP: &idpkg.LDAPConfig{Host: "ldap.example.com", Port: 389, Security: "none",
			BindDN: "cn=reader", BindPassword: "bind-secret-password", BaseDN: "dc=example"}}}))

	// They are stored encrypted.
	var shareKey, ruleKey, idpConfig string
	require.NoError(t, s.db.QueryRow(`SELECT secret_key FROM shares WHERE id = ?`, share.ID).Scan(&shareKey))
	require.NoError(t, s.db.QueryRow(`SELECT destination_secret_key FROM replication_rules WHERE id = 'rule-1'`).Scan(&ruleKey))
	require.NoError(t, s.db.QueryRow(`SELECT config FROM identity_providers WHERE id = 'idp-1'`).Scan(&idpConfig))
	assert.NotContains(t, shareKey, "share-secret-key")
	assert.NotContains(t, ruleKey, "rule-secret-key")
	assert.NotContains(t, idpConfig, "bind-secret-password")
	var stored idpkg.ProviderConfig
	require.NoError(t, json.Unmarshal([]byte(idpConfig), &stored))
	plain, err := idpkg.Decrypt(stored.LDAP.BindPassword, s.encSecret.Current())
	require.NoError(t, err, "encrypted with the node's secret")
	assert.Equal(t, "bind-secret-password", plain)
	return share.ID
}

// assertCredentialsRead reads back, on s, what storeCredentials stored.
func assertCredentialsRead(t *testing.T, s *Server, shareID string) {
	t.Helper()
	ctx := context.Background()
	gotShare, err := s.shareManager.GetShare(ctx, shareID)
	require.NoError(t, err)
	assert.Equal(t, "share-secret-key", gotShare.SecretKey)
	gotRule, err := s.replicationManager.GetRule(ctx, "rule-1")
	require.NoError(t, err)
	assert.Equal(t, "rule-secret-key", gotRule.DestinationSecretKey)
	gotIDP, err := s.idpManager.GetProvider(ctx, "idp-1")
	require.NoError(t, err)
	assert.Equal(t, "bind-secret-password", gotIDP.Config.LDAP.BindPassword)
}

// The credentials a server stores are decrypted after a restart with the
// default configuration: the secret is kept in the database, not derived from
// a JWT secret generated each start.
func TestStoredCredentialsSurviveARestart(t *testing.T) {
	dir, err := os.MkdirTemp("", "maxiofs-restart-secrets-*")
	require.NoError(t, err)
	defer os.RemoveAll(dir)

	first := startAt(t, dir)
	shareID := storeCredentials(t, first)
	require.NoError(t, first.shutdown())

	second := startAt(t, dir)
	defer second.shutdown() //nolint:errcheck
	assertCredentialsRead(t, second, shareID)
}

// A deployment that set auth.jwt_secret but not auth.encryption_secret
// encrypted with the JWT secret: its first start keeps using it. A generated
// JWT secret is not used.
func TestAnExplicitJWTSecretSeedsTheEncryptionSecret(t *testing.T) {
	explicit := newClusterTestNodeWith(t, func(c *config.Config) { c.Auth.EncryptionSecret = "" })
	assert.Equal(t, "test-jwt-secret-shared", explicit.encSecret.Current())
	generated := newClusterTestNodeWith(t, func(c *config.Config) {
		c.Auth.EncryptionSecret = ""
		c.Auth.JWTSecretAutoGenerated = true
	})
	assert.NotEqual(t, "test-jwt-secret-shared", generated.encSecret.Current())
}

// A node that joins a cluster takes its encryption secret: the credentials it
// stored before are re-encrypted with it and still read.
func TestJoiningNodeTakesTheClusterEncryptionSecret(t *testing.T) {
	a := newClusterTestNodeWith(t, func(c *config.Config) { c.Auth.EncryptionSecret = "secret-of-a" })
	b := newClusterTestNodeWith(t, func(c *config.Config) {
		c.Auth.EncryptionSecret = "secret-of-b"
		c.ClusterListen = "127.0.0.1:0"
	})
	ctx := context.Background()
	shareID := storeCredentials(t, b)
	consoleB := httptest.NewServer(b.consoleRouter)
	defer consoleB.Close()
	_, err := a.clusterManager.InitializeCluster(ctx, "a", "us-east-1", "https://127.0.0.1:18082")
	require.NoError(t, err)

	body, err := json.Marshal(map[string]string{"endpoint": consoleB.URL, "username": "admin", "password": "admin"})
	require.NoError(t, err)
	req := createAuthenticatedRequest(http.MethodPost, "/api/v1/cluster/nodes", strings.NewReader(string(body)), "", "admin", true)
	w := httptest.NewRecorder()
	a.handleAddClusterNode(w, req)
	require.Equal(t, http.StatusOK, w.Code, w.Body.String())

	assert.Equal(t, "secret-of-a", b.encSecret.Current())
	var stored string
	require.NoError(t, b.db.QueryRow(`SELECT secret FROM encryption_secret WHERE id = 1`).Scan(&stored))
	assert.Equal(t, "secret-of-a", stored)
	assertCredentialsRead(t, b, shareID)
}

// nodeSecretMatches reads, from s's list of cluster nodes, whether nodeID holds
// s's encryption secret; nil when it was not asked.
func nodeSecretMatches(t *testing.T, s *Server, nodeID string) *bool {
	t.Helper()
	req := createAuthenticatedRequest(http.MethodGet, "/api/v1/cluster/nodes", nil, "", "admin", true)
	w := httptest.NewRecorder()
	s.handleListClusterNodes(w, req)
	require.Equal(t, http.StatusOK, w.Code, w.Body.String())
	var out struct {
		Data struct {
			Nodes []clusterNodeResponse `json:"nodes"`
		} `json:"data"`
	}
	require.NoError(t, json.NewDecoder(w.Body).Decode(&out))
	for _, n := range out.Data.Nodes {
		if n.ID == nodeID {
			return n.EncryptionSecretMatches
		}
	}
	t.Fatalf("node %s not listed", nodeID)
	return nil
}

// The coordinator gives a node that holds another encryption secret its own;
// the node re-encrypts what it stores and takes it only from the coordinator
// it knows. The list of nodes shows whether each holds the same secret.
func TestCoordinatorGivesItsEncryptionSecret(t *testing.T) {
	p := newHAPair(t)
	ctx := context.Background()
	_, err := p.b.encSecret.Adopt(ctx, "secret-of-b")
	require.NoError(t, err)
	share, err := p.b.shareManager.CreateShare(ctx, "b", "k", "", "AKID", "share-secret-key", "u", nil)
	require.NoError(t, err)
	matches := nodeSecretMatches(t, p.a, p.bID)
	require.NotNil(t, matches)
	assert.False(t, *matches)
	lease := func(leader string) {
		t.Helper()
		require.NoError(t, p.b.leaderMgr.EnsureSchema())
		now := time.Now().Unix()
		_, err := p.b.db.Exec(`INSERT OR REPLACE INTO cluster_leader (id, leader_id, term, granted_at, expires_at) VALUES (1, ?, 1, ?, ?)`,
			leader, now, now+3600)
		require.NoError(t, err)
	}

	lease("someone-else")
	cluster.NewEncryptionSecretSync(p.a.clusterManager, fakeLeader(true), p.a.encSecret).SyncPeers(ctx)
	assert.Equal(t, "secret-of-b", p.b.encSecret.Current(), "only the coordinator sets it")

	lease(p.aID)
	cluster.NewEncryptionSecretSync(p.a.clusterManager, fakeLeader(false), p.a.encSecret).SyncPeers(ctx)
	assert.Equal(t, "secret-of-b", p.b.encSecret.Current(), "a node that is not the coordinator sends nothing")

	cluster.NewEncryptionSecretSync(p.a.clusterManager, fakeLeader(true), p.a.encSecret).SyncPeers(ctx)
	assert.Equal(t, p.a.encSecret.Current(), p.b.encSecret.Current())
	got, err := p.b.shareManager.GetShare(ctx, share.ID)
	require.NoError(t, err)
	assert.Equal(t, "share-secret-key", got.SecretKey)
	matches = nodeSecretMatches(t, p.a, p.bID)
	require.NotNil(t, matches)
	assert.True(t, *matches)
}

// The JWT secret is never listed, read or changed through the settings.
func TestSettingsNeverShowTheJWTSecret(t *testing.T) {
	server := getSharedServer()
	var rows int
	require.NoError(t, server.db.QueryRow(`SELECT COUNT(*) FROM system_settings WHERE key = 'jwt_secret'`).Scan(&rows))
	require.Equal(t, 1, rows, "the secret is stored with the settings")

	for _, path := range []string{"/api/v1/settings", "/api/v1/settings?category=security"} {
		req := createAuthenticatedRequest(http.MethodGet, path, nil, "", "global-admin", true)
		w := httptest.NewRecorder()
		server.handleListSettings(w, req)
		require.Equal(t, http.StatusOK, w.Code, w.Body.String())
		assert.NotContains(t, w.Body.String(), "jwt_secret", path)
		assert.Contains(t, w.Body.String(), `"key"`, "%s lists the other settings", path)
	}

	req := mux.SetURLVars(createAuthenticatedRequest(http.MethodGet, "/api/v1/settings/jwt_secret", nil, "", "global-admin", true),
		map[string]string{"key": "jwt_secret"})
	w := httptest.NewRecorder()
	server.handleGetSetting(w, req)
	assert.Equal(t, http.StatusNotFound, w.Code)

	req = mux.SetURLVars(createAuthenticatedRequest(http.MethodPut, "/api/v1/settings/jwt_secret", strings.NewReader(`{"value":"forged"}`), "", "global-admin", true),
		map[string]string{"key": "jwt_secret"})
	w = httptest.NewRecorder()
	server.handleUpdateSetting(w, req)
	assert.NotEqual(t, http.StatusOK, w.Code)
	var value string
	require.NoError(t, server.db.QueryRow(`SELECT value FROM system_settings WHERE key = 'jwt_secret'`).Scan(&value))
	assert.NotEqual(t, "forged", value)
}
